server:
  port: 8080

spring:
  application:
    name: velo-sentinel
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

velo:
  sentinel:
    routing-mode: SHADOW    # Options: TRITON, DYNAMO, SHADOW
    latency-threshold-ms: 200.0  # SLO for shadow mode comparisons

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

triton:
  grpc:
    host: localhost
    port: 8001
    model-name: simple

dynamo:
  grpc:
    host: localhost
    port: 9001

resilience4j:
  circuitbreaker:
    instances:
      dynamoBackend:
        registerHealthMap: true
        slidingWindowSize: 10              # Look at the last 10 calls
        failureRateThreshold: 50           # Open if 50% fail
        slowCallRateThreshold: 50          # Open if 50% are slow
        slowCallDurationThreshold: 500ms   # Define "slow" for local simulation
        waitDurationInOpenState: 10s       # Stay open for 10s before trying again
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    org:
      springframework:
        web: DEBUG
    # Optional: You can also monitor your own code's logic
    com:
      velo:
        sentinel: DEBUG