# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x16\x63om.velo.sentinel.grpc\"U\n\x16\x44ynamoInferenceRequest\x12\x13\n\x0binput_value\x18\x01 \x01(\x02\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\"=\n\x17\x44ynamoInferenceResponse\x12\x12\n\nprediction\x18\x01 \x01(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t2y\n\rDynamoService\x12h\n\x05Infer\x12..com.velo.sentinel.grpc.DynamoInferenceRequest\x1a/.com.velo.sentinel.grpc.DynamoInferenceResponseB*\n\x16\x63om.velo.sentinel.grpcB\x0eInferenceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.velo.sentinel.grpcB\016InferenceProtoP\001'
  _globals['_DYNAMOINFERENCEREQUEST']._serialized_start=43
  _globals['_DYNAMOINFERENCEREQUEST']._serialized_end=128
  _globals['_DYNAMOINFERENCERESPONSE']._serialized_start=130
  _globals['_DYNAMOINFERENCERESPONSE']._serialized_end=191
  _globals['_DYNAMOSERVICE']._serialized_start=193
  _globals['_DYNAMOSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
